spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
security:
  jwt:
    secret: YWRzYWRzYWRhc2Rhc2R1ZGh1YXNodWRnc2FnZHNnYXlkeWlnYXNnaWRnaXNhZGlsYXNpZ3VkYXNkc2E=
    access: 3600000
    refresh: 2592000000